name: TEIA CI

on:
  push:
    branches:
      - test
      - main
  pull_request:
    branches:
      - main

jobs:

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sitebackend

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Permissão Maven Wrapper
        run: chmod +x mvnw

      - name: Build + testes backend
        run: ./mvnw clean verify

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Executar testes frontend
        run: npm run test:run

      - name: Verificar ESLint
        run: npm run lint

  docker:
    runs-on: ubuntu-latest

    needs:
      - backend
      - frontend

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t teia-app -f TEIA.dockerfile .

      - name: Testar container
        run: |
          docker run -d --name teia-test -p 8080:8080 teia-app
          sleep 15
          docker ps
          docker stop teia-test